### ISSUE TITLE
Does not support IEnumerable<Model> as input to API

### ISSUE THREAD

**Issue by AndersMalmgren** [AnthonyGiretti/commonfeatures-webapi-aspnetcore#3]
Hi.
Great work with the tool!
I have followed the guide, there seems to be a problem. I have registered a validator 

`public class InvoiceValidation : AbstractValidator<Invoice>` 
The Api method takes a IEnumerable<Invoice> this does not trigger validation

Thanks

**Comment by AndersMalmgren** [comment]
Also chained expression would be super for dev friendliness :D

RuleFor(x => x.InvoiceKey.InvoiceNumber)
                .NotNull();

**Comment by AnthonyGiretti** [comment]
Hi!
Thank you for the feedback. But I'm not the  developer of the tool :)

I suggest you to contact the developer: https://fluentvalidation.net/

good luck!
